-- MySQL Script generated by MySQL Workbench
-- Tue Nov 29 04:49:38 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema tp4
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tp4
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tp4` ;
USE `tp4` ;

-- -----------------------------------------------------
-- Table `tp4`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tp4`.`curso` (
  `cod_curso` VARCHAR(255) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `alumno_Cod_matricula` VARCHAR(255) NOT NULL,
  `profesor_id_profesor` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`cod_curso`, `alumno_Cod_matricula`, `profesor_id_profesor`),
  INDEX `fk_curso_alumno1_idx` (`alumno_Cod_matricula` ASC) VISIBLE,
  INDEX `fk_curso_profesor1_idx` (`profesor_id_profesor` ASC) VISIBLE,
  CONSTRAINT `fk_curso_alumno1`
    FOREIGN KEY (`alumno_Cod_matricula`)
    REFERENCES `tp4`.`alumno` (`Cod_matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_curso_profesor1`
    FOREIGN KEY (`profesor_id_profesor`)
    REFERENCES `tp4`.`profesor` (`id_profesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tp4`.`profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tp4`.`profesor` (
  `id_profesor` VARCHAR(255) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `especialidad` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `curso_cod_curso` VARCHAR(255) NOT NULL,
  `curso_alumno_Cod_matricula` VARCHAR(255) NOT NULL,
  `curso_profesor_id_profesor` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_profesor`, `curso_cod_curso`, `curso_alumno_Cod_matricula`, `curso_profesor_id_profesor`),
  INDEX `fk_profesor_curso1_idx` (`curso_cod_curso` ASC, `curso_alumno_Cod_matricula` ASC, `curso_profesor_id_profesor` ASC) VISIBLE,
  CONSTRAINT `fk_profesor_curso1`
    FOREIGN KEY (`curso_cod_curso` , `curso_alumno_Cod_matricula` , `curso_profesor_id_profesor`)
    REFERENCES `tp4`.`curso` (`cod_curso` , `alumno_Cod_matricula` , `profesor_id_profesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tp4`.`alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tp4`.`alumno` (
  `Cod_matricula` VARCHAR(255) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `DNI` VARCHAR(45) NOT NULL,
  `Fechanacimiento` DATETIME NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `profesor_id_profesor` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`Cod_matricula`, `profesor_id_profesor`),
  INDEX `fk_alumno_profesor1_idx` (`profesor_id_profesor` ASC) VISIBLE,
  CONSTRAINT `fk_alumno_profesor1`
    FOREIGN KEY (`profesor_id_profesor`)
    REFERENCES `tp4`.`profesor` (`id_profesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
