-- MySQL Script generated by MySQL Workbench
-- Tue Nov 29 07:30:17 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ejercicio2
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ejerci3
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ejerci3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ejerci3` DEFAULT CHARACTER SET utf8mb4 ;
USE `ejerci3` ;

-- -----------------------------------------------------
-- Table `ejerci3`.`auto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ejerci3`.`auto` (
  `idauto` INT(11) NOT NULL,
  `numeromatricula` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `colordiseño` VARCHAR(45) NOT NULL,
  `precio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idauto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ejerci3`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ejerci3`.`cliente` (
  `cod_cliente` VARCHAR(55) NOT NULL,
  `clientecol` VARCHAR(45) NOT NULL,
  `dni` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `clientecol1` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_cliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ejerci3`.`reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ejerci3`.`reserva` (
  `id_reserva` INT(11) NOT NULL,
  `fechadereserva` DATETIME NOT NULL,
  `finreserva` DATETIME NOT NULL,
  `precio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_reserva`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ejerci3`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ejerci3`.`table1` (
  `cliente_cod_cliente` VARCHAR(55) NOT NULL,
  `reserva_id_reserva` INT(11) NOT NULL,
  PRIMARY KEY (`cliente_cod_cliente`, `reserva_id_reserva`),
  INDEX `fk_table1_reserva1_idx` (`reserva_id_reserva` ASC) VISIBLE,
  CONSTRAINT `fk_table1_cliente`
    FOREIGN KEY (`cliente_cod_cliente`)
    REFERENCES `ejerci3`.`cliente` (`cod_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_reserva1`
    FOREIGN KEY (`reserva_id_reserva`)
    REFERENCES `ejerci3`.`reserva` (`id_reserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ejerci3`.`table2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ejerci3`.`table2` (
  `reserva_id_reserva` INT(11) NOT NULL,
  `auto_idauto` INT(11) NOT NULL,
  PRIMARY KEY (`reserva_id_reserva`, `auto_idauto`),
  INDEX `fk_table2_auto1_idx` (`auto_idauto` ASC) VISIBLE,
  CONSTRAINT `fk_table2_reserva1`
    FOREIGN KEY (`reserva_id_reserva`)
    REFERENCES `ejerci3`.`reserva` (`id_reserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table2_auto1`
    FOREIGN KEY (`auto_idauto`)
    REFERENCES `ejerci3`.`auto` (`idauto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
